---
title: "Correlation movement algorithms "
author: "Matias Andina"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NA)
library(tidyverse)

```


Mouse was tracked by hand :( 

Read stuff

```{r}
source("calculate_distance.R")

truth <- read.table(file = "homecage/2020-01-31_14:21:23_manual_output.txt", sep="\t")
names(truth) <- c("frame", "seconds", "x", "y", "x_meters", "y_meters", "comment")

# modify the zero zeros
truth <- truth %>%
  mutate(x=ifelse(x * y == 0, NA, x),
         y=ifelse(x * y == 0, NA, y)) %>%
  # impute missing values
  mutate(x = runmed(zoo::na.locf(x), 31),
         y = runmed(zoo::na.locf(y), 31))


## set seed and add noise to hand scoring

set.seed(12345)
noise_x <- rnorm(nrow(truth), 0, 1)
noise_y <- rnorm(nrow(truth), 0, 1)
truth <- truth %>% mutate(x = x + noise_x, y = y + noise_y)


plot(truth$x, truth$y, type='l', xlab = "", ylab = "",
     main="Ground truth algorithm")
```

Make the datasets equal in length

```{r}

movement <- read.csv("homecage/2020-01-31_14:21:23_output_opt_flow.csv", header=FALSE)
# First value should be zero by definition
movement[1, 1] <- 0
names(movement) <- "movement"

# make them have same frame number
movement <- movement[1:6000, ]

```


Calculating distances

```{r}

truth <- calculate_distance(truth)
```


Plot things

```{r}
df <- cbind(truth, movement)

p_cor <- ggplot(df, aes(velocity, movement)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", color="red") +
  labs(title = "Correlation plot",
       subtitle = "Velocity is directly measured, movement is inferred.",
       x="velocity (px)", y ="movement (a.u.)") +
  annotate("text", x = 5, y = 40000,
           label = paste("r =",
                         round(cor(df$velocity, df$movement), 2))
  )


ggsave("corr_plot.png", plot = p_cor)

```



```{r}

p1 <- ggplot(df, aes(1:nrow(df), movement)) +
  geom_line() +
  labs(title = "Inferred movement", x="Time (frames)", y ="movement (a.u.)")
p2 <- ggplot(df, aes(1:nrow(df), velocity)) +
  geom_line(color="red") +
  labs(title = "Ground truth movement", x="Time (frames)", y ="velocity (px)")

p3 <- cowplot::plot_grid(p1, p2, nrow=2, align = "v")

ggsave(plot = p3, filename =  "movement_velocity.png", height = 7, width = 11)

```


```{r}
p_distance <- cowplot::plot_grid(
ggplot(df, aes(1:nrow(df), cumsum(movement))) + geom_line() + 
  labs(title = "Inferred cummulative distance", y = "integrated movement (a.u.)", x ="Time (frames)"),
ggplot(df, aes(1:nrow(df), distance)) + geom_line(color="red") +
  labs(title = "Cummulative distance", y = "distance (px)", x ="Time (frames)")
,
align = "h", nrow=2
)

ggsave("p_distance.png", plot = p_distance)
```

